### ISSUE TITLE
How to subscribe to the annotation controller events?

### ISSUE THREAD

**Issue by aramka** [Atalasoft/web-document-viewer-demo#14]
I have tried
        viewer.annotations.annotationcreated = (evnt, page) => {
            console.log("annotations created!!!")
            console.log(evnt);
            console.log(page);
        };
and

viewer.annotations.addEventListener("annotationcreated", (evnt, page) => {
            console.log("annotations created!!!")
            console.log(evnt);
            console.log(page);
        });

also I tried

viewer.annotations.annotationcreated = this.annotationCreated;

but the functions are never hit.

How do I get a callback when annotations are created?

**Comment by gennady-ermakov** [comment]
Hi @aramka 
try this one 
viewer.bind('annotationcreated', (evnt, page) => {
console.log("annotations created!!!")
console.log(evnt);
console.log(page);
});
